# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 20:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0003_genericpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genericpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='GenericPage',
        ),
    ]
