# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-08 01:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_homepagegalleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homepagegalleryimage',
            name='page',
        ),
        migrations.DeleteModel(
            name='HomePageGalleryImage',
        ),
    ]
